// Mock Product Data — preparado para futura integração com Supabase
// Tabelas futuras: products, orders, favorites, users

const MOCK_PRODUCTS = [
  {
    id: 1,
    name: "Porta-Retrato Família 3D",
    price: 89.90,
    originalPrice: 119.90,
    category: "decoracao",
    description: "Um presente que guarda o sorriso de quem você mais ama. Cada detalhe moldado com carinho para eternizar sua família.",
    shortDescription: "Eternize sua família em uma peça única e delicada",
    sizes: ["Pequeno (10x15)", "Médio (15x20)", "Grande (20x30)"],
    colors: ["Branco Pérola", "Rosa Queimado", "Natural"],
    images: [1, 2, 3],
    badge: "Mais Amado",
    rating: 4.9,
    reviews: 127,
    tags: ["família", "presente", "decoração", "mãe"],
    personalizationFields: ["name", "date", "message"],
    featured: true,
    inStock: true,
  },
  {
    id: 2,
    name: "Luminária Nome em 3D",
    price: 124.90,
    originalPrice: null,
    category: "luminaria",
    description: "Uma luz que aquece o coração. Seu nome ou o nome de quem você ama brilhando suavemente em cada cantinho.",
    shortDescription: "Seu nome iluminado com um brilho especial",
    sizes: ["Pequena", "Média", "Grande"],
    colors: ["Luz Quente", "Luz Fria", "RGB"],
    images: [2, 1, 3],
    badge: "Novo",
    rating: 4.8,
    reviews: 89,
    tags: ["luminária", "nome", "quarto", "bebê"],
    personalizationFields: ["name", "date", "message"],
    featured: true,
    inStock: true,
  },
  {
    id: 3,
    name: "Árvore Genealógica 3D",
    price: 159.90,
    originalPrice: 189.90,
    category: "decoracao",
    description: "Cada galho, um laço. Cada folha, uma história. Uma obra de arte que celebra as raízes da sua família.",
    shortDescription: "As raízes da sua família em arte tridimensional",
    sizes: ["Média (25x35)", "Grande (35x50)"],
    colors: ["Natural", "Dourado", "Branco Pérola"],
    images: [3, 1, 2],
    badge: "Especial",
    rating: 5.0,
    reviews: 64,
    tags: ["família", "árvore", "genealogia", "decoração"],
    personalizationFields: ["name", "date", "message"],
    featured: true,
    inStock: true,
  },
  {
    id: 4,
    name: "Cofre Personalizado",
    price: 79.90,
    originalPrice: null,
    category: "utilidade",
    description: "Guarde seus tesouros mais preciosos — memórias, moedas e sonhos — em uma peça feita só para você.",
    shortDescription: "Seus tesouros guardados com muito amor",
    sizes: ["Pequeno", "Médio"],
    colors: ["Branco", "Rosa Queimado", "Verde Sálvia"],
    images: [1, 3, 2],
    badge: null,
    rating: 4.7,
    reviews: 43,
    tags: ["cofre", "presente", "infantil", "utilidade"],
    personalizationFields: ["name", "message"],
    featured: false,
    inStock: true,
  },
  {
    id: 5,
    name: "Boneco(a) Personalizado(a)",
    price: 149.90,
    originalPrice: 179.90,
    category: "miniatura",
    description: "Uma versão em miniatura da pessoa mais especial da sua vida. Um presente que causa lágrimas de alegria.",
    shortDescription: "Uma miniatura com toda a personalidade de quem você ama",
    sizes: ["10cm", "15cm", "20cm"],
    colors: ["Colorido", "Natural", "Personalizado"],
    images: [2, 3, 1],
    badge: "Exclusivo",
    rating: 4.9,
    reviews: 211,
    tags: ["boneco", "miniatura", "personalizado", "presente"],
    personalizationFields: ["name", "date", "message"],
    featured: true,
    inStock: true,
  },
  {
    id: 6,
    name: "Caixinha de Memórias",
    price: 99.90,
    originalPrice: null,
    category: "utilidade",
    description: "Uma caixinha para guardar os pedacinhos de amor: fotos, bilhetes, flores secas... memórias que nunca envelhecem.",
    shortDescription: "O lugar perfeito para guardar o que importa",
    sizes: ["Pequena", "Média", "Grande"],
    colors: ["Branco Pérola", "Rosa Queimado", "Bege"],
    images: [3, 2, 1],
    badge: null,
    rating: 4.8,
    reviews: 76,
    tags: ["caixinha", "memórias", "presente", "mãe"],
    personalizationFields: ["name", "date", "message"],
    featured: false,
    inStock: true,
  },
  {
    id: 7,
    name: "Placa de Rua Personalizada",
    price: 69.90,
    originalPrice: null,
    category: "decoracao",
    description: "Seu endereço emocional: o lar onde o amor mora. Uma placa linda com o nome da sua família.",
    shortDescription: "O nome da sua família em destaque especial",
    sizes: ["Pequena (10x20)", "Média (15x30)"],
    colors: ["Preto Fosco", "Branco", "Bronze"],
    images: [1, 2, 3],
    badge: null,
    rating: 4.6,
    reviews: 38,
    tags: ["placa", "casa", "família", "decoração"],
    personalizationFields: ["name", "message"],
    featured: false,
    inStock: true,
  },
  {
    id: 8,
    name: "Quadro de Letras 3D",
    price: 109.90,
    originalPrice: 129.90,
    category: "decoracao",
    description: "Palavras que decoram e emocionam. Escolha a frase que define sua família e transforme em arte tridimensional.",
    shortDescription: "As palavras certas em uma arte que toca o coração",
    sizes: ["Médio (20x40)", "Grande (30x60)"],
    colors: ["Branco", "Rosa Queimado", "Verde Sálvia"],
    images: [2, 1, 3],
    badge: "Tendência",
    rating: 4.7,
    reviews: 95,
    tags: ["quadro", "letras", "frase", "decoração"],
    personalizationFields: ["name", "date", "message"],
    featured: true,
    inStock: true,
  },
];

const MOCK_TESTIMONIALS = [
  {
    id: 1,
    name: "Ana Paula M.",
    location: "São Paulo, SP",
    text: "Fiz o porta-retrato com a foto da minha mãe e ela chorou de emoção. Foi o presente mais especial que já dei na vida. Parece que capturaram a alma dela naquela peça.",
    product: "Porta-Retrato Família 3D",
    rating: 5,
    avatar: "AP",
  },
  {
    id: 2,
    name: "Carla S.",
    location: "Belo Horizonte, MG",
    text: "A luminária com o nome da minha filha ficou perfeita no quartinho dela. Toda noite ela pede pra acender 'a luz do meu nome'. Isso não tem preço.",
    product: "Luminária Nome em 3D",
    rating: 5,
    avatar: "CS",
  },
  {
    id: 3,
    name: "Fernanda R.",
    location: "Curitiba, PR",
    text: "O boneco personalizado do meu marido ficou igualzinho a ele! Até o jeito de sorrir. Meus filhos adoraram e ficam brincando com ele todo dia.",
    product: "Boneco(a) Personalizado(a)",
    rating: 5,
    avatar: "FR",
  },
  {
    id: 4,
    name: "Juliana T.",
    location: "Rio de Janeiro, RJ",
    text: "A árvore genealógica ficou uma obra de arte. Coloquei os nomes de quatro gerações. Toda vez que recebo visita, todo mundo fica admirando.",
    product: "Árvore Genealógica 3D",
    rating: 5,
    avatar: "JT",
  },
];

const CATEGORIES = [
  { id: "todos", label: "Todos" },
  { id: "decoracao", label: "Decoração" },
  { id: "luminaria", label: "Luminárias" },
  { id: "miniatura", label: "Miniaturas" },
  { id: "utilidade", label: "Utilidades" },
];

const WHATSAPP_NUMBER = "5511999999999"; // Substituir pelo número real
